xen-network.bb: don't use "\n" in echo command
"\n" handling is wildly varies between shells. Some shells replace it
with line feed, other just print it as is (i.e. literally \n). This
causes hard to debug issues with the build. This particular case led
to the following error:

```
ERROR: Logfile of failure stored in: /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/temp/log.do_image.1535569
Log data follows:
| DEBUG: Executing python function do_image
| NOTE: Executing systemd_preset_all ...
| DEBUG: Executing shell function systemd_preset_all
| ln -s /lib/systemd/system/systemd-userdbd.socket /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/rootfs/etc/systemd/system/so
ckets.target.wants/systemd-userdbd.socket
| ln -s /lib/systemd/system/systemd-timesyncd.service /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/rootfs/etc/systemd/system
/sysinit.target.wants/systemd-timesyncd.service
| ln -s /lib/systemd/system/systemd-timesyncd.service /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/rootfs/etc/systemd/system
/dbus-org.freedesktop.timesync1.service
| Traceback (most recent call last):
|   File "/home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/recipe-sysroot-native/usr/bin/systemctl", line 350, in <module>
|     main()
|   File "/home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/recipe-sysroot-native/usr/bin/systemctl", line 344, in main
|     preset_all(root)
|   File "/home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/recipe-sysroot-native/usr/bin/systemctl", line 285, in preset_all
|     SystemdUnit(root, service).enable()
|   File "/home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/recipe-sysroot-native/usr/bin/systemctl", line 221, in enable
|     config = SystemdFile(self.root, path, instance_unit_name)
|   File "/home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/recipe-sysroot-native/usr/bin/systemctl", line 39, in __init__
|     self._parse(root, path2)
|   File "/home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/recipe-sysroot-native/usr/bin/systemctl", line 79, in _parse
|     k = m.group('key')
| AttributeError: 'NoneType' object has no attribute 'group'
| WARNING: /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/temp/run.systemd_preset_all.1535569:150 exit 1 from 'systemctl --roo
t="/home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/rootfs" --preset-mode=enable-only preset-all'
| WARNING: Backtrace (BB generated script):
|       #1: systemd_preset_all, /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/temp/run.systemd_preset_all.1535569, line 150
|       #2: main, /home/lorc/work/prod-devel-salvator-8g/yocto/build-domd/tmp/work/salvator_x-poky-linux/core-image-weston/1.0-r0/temp/run.systemd_preset_all.1535569, line 154
| DEBUG: Python function do_image finished
ERROR: Task (/home/lorc/work/prod-devel-salvator-8g/yocto/poky/meta/recipes-graphics/images/core-image-weston.bb:do_image) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4718 tasks of which 4316 didn't need to be rerun and 1 failed.
```

From this error message it is unclear what exactly caused the
error. It was found that Yocto script that emulates systemctl command
was not ready to see "\n" sequence in a systemd unit file.

To fix this issue we just remote "\n" from the "echo" command. This
will decrease readability of the resulting .service file a bit. Other
alternatives are to use empty echo "" command or use "printf" command
that correctly handles "\n" sequence across all shells. But both those
options will impair readability in .bb file, so I prefer the first
solution.

Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
Acked-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>