security: optee-ta-devkit: move recipe logic to include file
All other optee recipes have most of the logic inside the .inc files,
which eases up adding a new version: just create new optee-XXX_${PV}.bb
file, include optee-XXX.inc and provide SRC_URI. But, in case of
optee-ta-devkit recipe all the stuff is held in .bb file itself, which
is inconvenient, because if we want to add a new -tavkit version, we
will need to copy the whole file.

This patch moves optee-ta-devkit.bb into include file, to align it
with other recipes.

The unfortunate consequence for this is the fact that BitBake tries to
determine value of PV variable based on file name, and in this case it
will happen when parsing .inc file, not .bb file. So it will set PV to
default value "1.0" which will lead to build failure:

ERROR: ParseError at meta-xt-common/meta-xt-security/recipes-security/optee/optee-os-tadevkit.inc:1: Could not include required file recipes-security/optee/optee-os_1.0.bb

So, we need to set PV manually in optee-tadevkit_4.1.0.bb.

Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
Acked-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>